### ISSUE TITLE
没有修改vmess端口选项，希望大神能增加这一选项。

### ISSUE THREAD

**Issue by ssfeng72** [eooce/Sing-box#11]
1. 修改vless-reality端口
------------
2. 修改hysteria2端口
------------
3. 修改tuic端口
------------
4. 返回上一级菜单
------------
为什么没有修改vmess端口选项，希望能增加这一选项。duckyci这种小鸡分配了有限的固定端口，默认部署的随机端口不在有限的固定端口范围内，导致vmess节点无法使用。增加修改vmess端口选项，可以把vmess节点端口修改为duckyci这种小鸡分配的固定端口，这样vmess节点就可以使用了。非常感谢！

**Comment by eooce** [comment]
vmess-ws-tls使用的argo隧道，随意不需要端口，所以没必要修改，随意端口即可通，不通就单独测一下，没问题的

**Comment by ssfeng72** [comment]
比如duckyci这种小鸡分配给我的端口范围是20652-20700，增加固定隧道不通，是不是随意的端口不在20652-20700范围内所致。而serv00指定端口，使用临时隧道则可连通上网，另，serv00如何增加固定隧道，还有serv00为什么服务器地址是85.194.244.91，而不是serv00分配给我的地址。

**Comment by ssfeng72** [comment]
"argo隧道端口，固定隧道token需和cloudflare后台设置的一致".我不知道vmess端口怎么设置cloudflare后台端口，怎么保持一致？
