### ISSUE TITLE
Serv00 一键三协议安装脚本能不能增加Vmess+ws或者VMess+argo协议？

### ISSUE THREAD

**Issue by crosspacific** [eooce/Sing-box#13]
你好，请问Serv00 一键三协议安装脚本能不能增加Vmess+ws或者VMess+argo协议？主要是想同时使用reality和vm这两个协议。谢谢。

**Comment by eooce** [comment]
reality在serv00中的表现并不好，建议使用一建4协议脚本，里面包含vmess-argo协议
