### ISSUE TITLE
serv00服务器地址为什么是85.194.244.91，而不是serv00分配给我的地址。如果serv00节点停止运行，怎么重新启动。

### ISSUE THREAD

**Issue by ssfeng72** [eooce/Sing-box#15]
serv00服务器地址为什么是85.194.244.91，而不是serv00分配给我的地址。如果serv00节点停止运行，怎么重新启动。设置固定隧道ping不通，临时隧道就可以ping通，问题出在哪？

**Comment by eooce** [comment]
分配的是域名，连接ssh的，域名绑定到了服务器，IP就是服务器的真实IP，明白了吗？
固定隧道不通是因为你设置得不对，serv00的话，cloudflare隧道端口需和serv00面板开放的tcp端口一致，脚本中已经提示，麻烦看清楚一点啊

**Comment by ssfeng72** [comment]
“cloudflare隧道端口需和serv00面板开放的tcp端口一致”，怎么设置？比如serv00面板开放的tcp端口是3324，cloudflare隧道端口在哪里设置这个3324端口？
