### ISSUE TITLE
serv00 哪吒怎么更新？

### ISSUE THREAD

**Issue by huha121** [eooce/Sing-box#2]
不然不显示国旗

**Comment by eooce** [comment]
一键降级面板
bash <(curl -Ls https://raw.githubusercontent.com/eooce/scripts/master/nezha.sh)

**Comment by zscontinent** [comment]
> 一键降级面板 bash <(curl -Ls https://raw.githubusercontent.com/eooce/scripts/master/nezha.sh)

Serv00无法执行，请提供具体命令

**Comment by dzss3399** [comment]
vps重启了，怎么再次启动已有节点

**Comment by eooce** [comment]
重新安装
