### ISSUE TITLE
域名eooce.2go.us.kg无法访问呢

### ISSUE THREAD

**Issue by donggua1118** [eooce/Sing-box#20]
![1723989593556](https://github.com/user-attachments/assets/6e75685d-04f8-401c-8eae-b0f4ddd3a31f)
请问大佬，这个无法拉取啊，这个错误影响吗？

**Comment by eooce** [comment]
机子问题，换个时间试试，

**Comment by siren202101** [comment]
> 机子问题，换个时间尝试，

我的也是这个错误，无法使用节点了

**Comment by eooce** [comment]
机子问题，s9有这样的情况，前面的机子没问题，ct8正常，可以玩ct8，www.ct8.pl
