### ISSUE TITLE
脚本怎么保活

### ISSUE THREAD

**Issue by tyy840913** [eooce/Sing-box#21]
刚用这个脚本，不知道怎么保活

**Comment by eooce** [comment]
不用保活

**Comment by pcmaclk** [comment]
昨天装的Serv00一键三协议，今天就连接不上了，查了状态，显示没安装，应该是重启后清除了，所以求个保活的招

**Comment by eooce** [comment]
机子不稳定导致的吧，根本不用保活，不掉的啊，你装了其他的东西就不能保证了
