### ISSUE TITLE
ssh工具箱能修改下默认的K快捷指令么，还有可以加个卸载工具箱的指令么

### ISSUE THREAD

**Issue by tiancool** [eooce/Sing-box#30]
和 科技lion kejilion的原版脚本工具箱 快捷指令冲突太严重了，删也删不掉，有点尴尬，不如你改为自己的名字开头的 e 快捷指令

**Comment by eooce** [comment]
系统工具里可以自己设置别的快捷键

**Comment by tiancool** [comment]
> 系统工具里可以自己设置别的快捷键
> 
> 

不生效，也删除不了呢

**Comment by eooce** [comment]
可以的，先更新脚本再去设置
