### ISSUE TITLE
tuic shell::: curl: (28) Operation timed out after 2859 milliseconds with 12499238 out of 17313792 bytes received

### ISSUE THREAD

**Issue by mxyhi** [eooce/Sing-box#31]
PORT=8112 bash <(curl -Ls https://00.2go.us.kg/tu.sh) 

Downloading ./gfQWST by wget
curl: (28) Operation timed out after 2859 milliseconds with 12499238 out of 17313792 bytes received

**Comment by eooce** [comment]
机子卡了，换个时间再试
