### ISSUE TITLE
想请问下clash节点怎么搓，v2ray直接粘贴就可以上了，clash死活搓不出来

### ISSUE THREAD

**Issue by sliploach** [eooce/Sing-box#33]
想请问下clash节点怎么搓，v2ray直接粘贴就可以上了，clash死活搓不出来

name: serv00 #可自定义名称
type: vmess
server: [www.visa.com.tw](http://www.visa.com.tw/) #解析的域名或者优选域名IP
port: 443 #自定义的端口
uuid: #自定义的uuid
alterId: 0
cipher: auto
skip-cert-verify: true
udp: true
tls: true
network: ws
servername: #sni域名，与下面的host一致
ws-opts:
path: "/vmess" #自定义的path路径
headers:
Host:

**Comment by eooce** [comment]
订阅转换：https://sublink-worker.sageer.me

**Comment by eooce** [comment]
proxies:
- name: vless-tcp-reality             
  type: vless
  server: $server_ip                           
  port: $vless_port                                
  uuid: $uuid   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.iij.ad.jp                 
  reality-opts: 
    public-key: $public_key   
    short-id:
  client-fingerprint: chrome                  

- name: vmess-ws-argo                    
  type: vmess
  server: www.gov.tw                        
  port: 443                                     
  uuid: $uuid       
  alterId: 0
  cipher: auto
  udp: flase
  tls: true
  network: ws
  servername: $argodomain                   
  ws-opts:
    path: "/vmess?ed=2048"                             
    headers:
      Host: $argodomain
  alpn: 
  fp: chrome                    

- name: hysteria2  
  type: hysteria2                        
  server: $server_ip                           
  port: $hy2_port                                                          
  password: $uuid                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true

- name: tuic5                                                             
  type: tuic
  server: $server_ip                           
  port: $tuic_port                                                          
  uuid: $uuid       
  password:  
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true

**Comment by sliploach** [comment]
感谢回复，但是没成功。我主要是用vmess+ws+argo，cf已经配置好了，域名也有，关键是v2ray是可以正常使用的，至少说明cf的配置应该是没问题的。这个问题着实另人抓狂，我都搓了一晚上了
第一，用订阅转换，不经任何修改，clash无法连接
第二，按照你说的手搓节点，仍然无法连接，附上修改后的节点配置：
- name: serv00-argo                           
    type: vmess
    server: www.visa.com.tw
    port: 443
    uuid: 
    alterId: 0
    cipher: auto
    udp: false
    tls: true
    network: ws
    servername: abc.abc.buzz
    ws-opts:
      path: "/vmess?ed=2048"
      headers:
        Host: abc.abc.buzz
    alpn: [h3]

**Comment by sliploach** [comment]
使用的是PORT=TCP端口 bash <(curl -Ls https://raw.githubusercontent.com/eooce/scripts/master/containers-shell/00_vmess.sh) 这个安装的，自己加了uuid的参数，看了源码，好像仍然是使用的源码中的uuid

**Comment by eooce** [comment]
前面加UUID=自定义的uuid 变量    clash配置我试过的，没问题的，可能软件设置问题

**Comment by sliploach** [comment]
有可能吧，我在singbox里面也配置成功了，对比了一下双方的配置，似乎sing box有一个network：tcp这个配置，clash好像没有这个语法，它的network只能是：ws。

**Comment by sliploach** [comment]
再次折腾了许久，发现如下方案：
1、关闭clash服务模式，关闭tun模式，关闭dns，链接就通了，不知其原理
2、vmess+ws+argo，优选ip无法使用，一旦改为优选ip，节点不通
3、singbox的进程规则从来没有成功过，不知是否有什么注意事项，没有软路由，纯电脑客户端使用
