### ISSUE TITLE
argo连接失败

### ISSUE THREAD

**Issue by Winyer** [eooce/Sing-box#40]
11月24号发生的，重新搭建也一样，望修复

**Comment by qq1012827513** [comment]
确实不行了 研究了一下配置固定域名 搞定了

**Comment by Winyer** [comment]
> 确实不行了 研究了一下配置固定域名 搞定了

大佬，怎么搞的？

**Comment by qq1012827513** [comment]
> > 确实不行了 研究了一下配置固定域名 搞定了
> 
> 大佬，怎么搞的？

首先你需要有个在cf下的域名然后菜单里选择添加Argo固定隧道，打开提示里面的网页授权之后把json复制进去就可以用自己的域名建立隧道了

**Comment by Winyer** [comment]
> > > 确实不行了 研究了一下配置固定域名 搞定了
> > 
> > 
> > 大佬，怎么搞的？
> 
> 首先你需要有个在cf下的域名然后菜单里选择添加Argo固定隧道，打开提示里面的网页授权之后把json复制进去就可以用自己的域名建立隧道了

谢谢大佬，我去试试

**Comment by eooce** [comment]
cf问题，等cf修复吧

**Comment by Winyer** [comment]
> cf问题，等cf修复吧

网上说不会恢复了....

**Comment by Winyer** [comment]
> cf问题，等cf修复吧

Serv00|CT8 hysteria2也不能用了

**Comment by eooce** [comment]
那说明ip墙了，万人骑的，很正常
