### ISSUE TITLE
serv00提供三个ip，恳请增加选择ip功能，可选择没有被墙的ip搭建节点。

### ISSUE THREAD

**Issue by ssfeng72** [eooce/Sing-box#45]
您的脚本很好用，但存在一个大问题，您的脚本搭建在serv00默认被墙的ip上，hy2和tuic5节点自搭建好就不能用。而serv00提供三个ip，一个主ip被墙，另两个没有被墙。恳请增加选择ip功能，可选择没有被墙的ip搭建节点，这样搭建的hy2和tuic5节点就可以用了。万分感谢！！！

**Comment by eooce** [comment]
自动选择可用ip的
