### ISSUE TITLE
sver00节点全都不通,咋回事?

### ISSUE THREAD

**Issue by 10000-ok** [eooce/Sing-box#5]
这脚本sver00搭出来的节点都不通啊,无论reality还是hy2都不通,怎么回事呢?哪的问题?完全按步骤安装

**Comment by eooce** [comment]
面板运行程序的权限，端口开放符合要求，并且和输入的匹配，客户端跳过证书验证设置为true，还不通就是机子问题，有的服务器ip是被墙的，建议新注册的s8

**Comment by eooce** [comment]
面板运行程序的权限，端口开放符合要求，并且和输入的匹配，客户端跳过证书验证设置为true，还不通就是机子问题，有的服务器ip是被墙的，建议新注册的s8

**Comment by 10000-ok** [comment]
> 面板运行程序的权限，端口开放符合要求，并且和输入的匹配，客户端跳过证书验证设置为true，还不通就是机子问题，有的服务器ip是被墙的，建议新注册的s8

端口开放就是一个TCP和两个UDP嘛,还要别的要求吗?权限开了,证书验证也跳过了.我在s5和s7都试过了, 不通

**Comment by 10000-ok** [comment]
> 面板运行程序的权限，端口开放符合要求，并且和输入的匹配，客户端跳过证书验证设置为true，还不通就是机子问题，有的服务器ip是被墙的，建议新注册的s8

注册了S8终于通了,非常感谢.  顺便再问两个问题: 这些节点的安装路径在哪? 还有一个就是,装了这些节点还能安装pm2进程吗?如果节点挂了,想用pm2恢复它们该怎么设置路径.求解答,十分感谢

**Comment by eooce** [comment]
安装路径再domains/域名/logs/里，pm2别装了，装了必挂，或封号，要的是低占用的健康状态
