### ISSUE TITLE
想问一下tunnel选择那种方式创建呢

### ISSUE THREAD

**Issue by shylock-wu** [eooce/Sing-box#7]
好像没有serve00的系统类型啊
![CleanShot 2024-08-05 at 20 39 17@2x](https://github.com/user-attachments/assets/adb008fb-903a-4335-a2bf-ef8d32a63cd9)

**Comment by eooce** [comment]
随便哪个，token都一样，端口要设置为serv00上开放的tcp端口一致，不会建议用临时隧道
